### YamlMime:ManagedReference
items:
- uid: RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm
  commentId: T:RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm
  id: PickConfigurationDomainPathForm
  parent: RobotComponents.ABB.Controllers.Forms
  children:
  - RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm.#ctor(RobotComponents.ABB.Controllers.Controller)
  - RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm.Attribute
  - RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm.Domain
  - RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm.Instance
  - RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm.Type
  langs:
  - csharp
  - vb
  name: PickConfigurationDomainPathForm
  nameWithType: PickConfigurationDomainPathForm
  fullName: RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm
  type: Class
  assemblies:
  - RobotComponents.ABB.Controllers
  namespace: RobotComponents.ABB.Controllers.Forms
  summary: Represents the pick configuration domain form class.
  example: []
  syntax:
    content: 'public class PickConfigurationDomainPathForm : Dialog<bool>'
    content.vb: Public Class PickConfigurationDomainPathForm Inherits Dialog(Of Boolean)
  inheritance:
  - System.Object
- uid: RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm.#ctor(RobotComponents.ABB.Controllers.Controller)
  commentId: M:RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm.#ctor(RobotComponents.ABB.Controllers.Controller)
  id: '#ctor(RobotComponents.ABB.Controllers.Controller)'
  parent: RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm
  langs:
  - csharp
  - vb
  name: PickConfigurationDomainPathForm(Controller)
  nameWithType: PickConfigurationDomainPathForm.PickConfigurationDomainPathForm(Controller)
  fullName: RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm.PickConfigurationDomainPathForm(RobotComponents.ABB.Controllers.Controller)
  type: Constructor
  assemblies:
  - RobotComponents.ABB.Controllers
  namespace: RobotComponents.ABB.Controllers.Forms
  summary: Constructs the form.
  example: []
  syntax:
    content: public PickConfigurationDomainPathForm(Controller controller)
    parameters:
    - id: controller
      type: RobotComponents.ABB.Controllers.Controller
      description: The controller to read from.
    content.vb: Public Sub New(controller As Controller)
  overload: RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm.#ctor*
  nameWithType.vb: PickConfigurationDomainPathForm.New(Controller)
  fullName.vb: RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm.New(RobotComponents.ABB.Controllers.Controller)
  name.vb: New(Controller)
- uid: RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm.Domain
  commentId: P:RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm.Domain
  id: Domain
  parent: RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm
  langs:
  - csharp
  - vb
  name: Domain
  nameWithType: PickConfigurationDomainPathForm.Domain
  fullName: RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm.Domain
  type: Property
  assemblies:
  - RobotComponents.ABB.Controllers
  namespace: RobotComponents.ABB.Controllers.Forms
  summary: Gets the name of the domain.
  example: []
  syntax:
    content: public string Domain { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property Domain As String
  overload: RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm.Domain*
- uid: RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm.Type
  commentId: P:RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm.Type
  id: Type
  parent: RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm
  langs:
  - csharp
  - vb
  name: Type
  nameWithType: PickConfigurationDomainPathForm.Type
  fullName: RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm.Type
  type: Property
  assemblies:
  - RobotComponents.ABB.Controllers
  namespace: RobotComponents.ABB.Controllers.Forms
  summary: Gets the type name.
  example: []
  syntax:
    content: public string Type { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property Type As String
  overload: RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm.Type*
- uid: RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm.Instance
  commentId: P:RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm.Instance
  id: Instance
  parent: RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm
  langs:
  - csharp
  - vb
  name: Instance
  nameWithType: PickConfigurationDomainPathForm.Instance
  fullName: RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm.Instance
  type: Property
  assemblies:
  - RobotComponents.ABB.Controllers
  namespace: RobotComponents.ABB.Controllers.Forms
  summary: Gets the name of the instance.
  example: []
  syntax:
    content: public string Instance { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property Instance As String
  overload: RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm.Instance*
- uid: RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm.Attribute
  commentId: P:RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm.Attribute
  id: Attribute
  parent: RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm
  langs:
  - csharp
  - vb
  name: Attribute
  nameWithType: PickConfigurationDomainPathForm.Attribute
  fullName: RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm.Attribute
  type: Property
  assemblies:
  - RobotComponents.ABB.Controllers
  namespace: RobotComponents.ABB.Controllers.Forms
  summary: Gets the name of the attribute.
  example: []
  syntax:
    content: public string Attribute { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property Attribute As String
  overload: RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm.Attribute*
references:
- uid: RobotComponents.ABB.Controllers.Forms
  commentId: N:RobotComponents.ABB.Controllers.Forms
  isExternal: true
  href: RobotComponents.html
  name: RobotComponents.ABB.Controllers.Forms
  nameWithType: RobotComponents.ABB.Controllers.Forms
  fullName: RobotComponents.ABB.Controllers.Forms
  spec.csharp:
  - uid: RobotComponents
    name: RobotComponents
    isExternal: true
    href: RobotComponents.html
  - name: .
  - uid: RobotComponents.ABB
    name: ABB
    isExternal: true
    href: RobotComponents.ABB.html
  - name: .
  - uid: RobotComponents.ABB.Controllers
    name: Controllers
    isExternal: true
    href: RobotComponents.ABB.Controllers.html
  - name: .
  - uid: RobotComponents.ABB.Controllers.Forms
    name: Forms
    isExternal: true
    href: RobotComponents.ABB.Controllers.Forms.html
  spec.vb:
  - uid: RobotComponents
    name: RobotComponents
    isExternal: true
    href: RobotComponents.html
  - name: .
  - uid: RobotComponents.ABB
    name: ABB
    isExternal: true
    href: RobotComponents.ABB.html
  - name: .
  - uid: RobotComponents.ABB.Controllers
    name: Controllers
    isExternal: true
    href: RobotComponents.ABB.Controllers.html
  - name: .
  - uid: RobotComponents.ABB.Controllers.Forms
    name: Forms
    isExternal: true
    href: RobotComponents.ABB.Controllers.Forms.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm.#ctor*
  commentId: Overload:RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm.#ctor
  isExternal: true
  href: RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm.html#RobotComponents_ABB_Controllers_Forms_PickConfigurationDomainPathForm__ctor_RobotComponents_ABB_Controllers_Controller_
  name: PickConfigurationDomainPathForm
  nameWithType: PickConfigurationDomainPathForm.PickConfigurationDomainPathForm
  fullName: RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm.PickConfigurationDomainPathForm
  nameWithType.vb: PickConfigurationDomainPathForm.New
  fullName.vb: RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm.New
  name.vb: New
- uid: RobotComponents.ABB.Controllers.Controller
  commentId: T:RobotComponents.ABB.Controllers.Controller
  parent: RobotComponents.ABB.Controllers
  isExternal: true
  href: RobotComponents.ABB.Controllers.Controller.html
  name: Controller
  nameWithType: Controller
  fullName: RobotComponents.ABB.Controllers.Controller
- uid: RobotComponents.ABB.Controllers
  commentId: N:RobotComponents.ABB.Controllers
  isExternal: true
  href: RobotComponents.html
  name: RobotComponents.ABB.Controllers
  nameWithType: RobotComponents.ABB.Controllers
  fullName: RobotComponents.ABB.Controllers
  spec.csharp:
  - uid: RobotComponents
    name: RobotComponents
    isExternal: true
    href: RobotComponents.html
  - name: .
  - uid: RobotComponents.ABB
    name: ABB
    isExternal: true
    href: RobotComponents.ABB.html
  - name: .
  - uid: RobotComponents.ABB.Controllers
    name: Controllers
    isExternal: true
    href: RobotComponents.ABB.Controllers.html
  spec.vb:
  - uid: RobotComponents
    name: RobotComponents
    isExternal: true
    href: RobotComponents.html
  - name: .
  - uid: RobotComponents.ABB
    name: ABB
    isExternal: true
    href: RobotComponents.ABB.html
  - name: .
  - uid: RobotComponents.ABB.Controllers
    name: Controllers
    isExternal: true
    href: RobotComponents.ABB.Controllers.html
- uid: RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm.Domain*
  commentId: Overload:RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm.Domain
  isExternal: true
  href: RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm.html#RobotComponents_ABB_Controllers_Forms_PickConfigurationDomainPathForm_Domain
  name: Domain
  nameWithType: PickConfigurationDomainPathForm.Domain
  fullName: RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm.Domain
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm.Type*
  commentId: Overload:RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm.Type
  isExternal: true
  href: RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm.html#RobotComponents_ABB_Controllers_Forms_PickConfigurationDomainPathForm_Type
  name: Type
  nameWithType: PickConfigurationDomainPathForm.Type
  fullName: RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm.Type
- uid: RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm.Instance*
  commentId: Overload:RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm.Instance
  isExternal: true
  href: RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm.html#RobotComponents_ABB_Controllers_Forms_PickConfigurationDomainPathForm_Instance
  name: Instance
  nameWithType: PickConfigurationDomainPathForm.Instance
  fullName: RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm.Instance
- uid: RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm.Attribute*
  commentId: Overload:RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm.Attribute
  isExternal: true
  href: RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm.html#RobotComponents_ABB_Controllers_Forms_PickConfigurationDomainPathForm_Attribute
  name: Attribute
  nameWithType: PickConfigurationDomainPathForm.Attribute
  fullName: RobotComponents.ABB.Controllers.Forms.PickConfigurationDomainPathForm.Attribute
